import * as assert from "assert";
import * as x509 from "../src";

context("OCSP", async () => {

  const pemLeaf = `-----BEGIN CERTIFICATE-----
MIICajCCAhGgAwIBAgIUfw1rwZ/YgkthPxrsy0Tq/epRLmMwCgYIKoZIzj0EAwIw
JjEVMBMGA1UEAxMMUm9vdCBDQSBjZXJ0MQ0wCwYDVQQKEwRUZXN0MB4XDTIyMTIy
NjA2NDIwNloXDTMyMTIyNjA2NDIwNlowLjEdMBsGA1UEAxMUSW50ZXJtZWRpYXRl
IENBIGNlcnQxDTALBgNVBAoTBFRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AATbkHNu+8Co/+TSG0Pufs/HEs5SELP39OCzKovPbUYSA8IHJF95Rh+wfPcOcLMk
b/r5Nb9WigwrJNosmdApaNbfo4IBEzCCAQ8wDgYDVR0PAQH/BAQDAgEGMBIGA1Ud
EwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFPu3XMGqhbPRsLmHqguYSBura+VTMB8G
A1UdIwQYMBaAFLlAZeqsu58hI2DV8kaz4aLR2YHbMDQGA1UdJQQtMCsGCCsGAQUF
BwMCBggrBgEFBQcDBAYKKwYBBAGCNwoDDAYJYIZIAYb6aygLMD4GCCsGAQUFBwEB
BDIwMDAuBggrBgEFBQcwAoYiaHR0cHM6Ly9sb2NhbGhvc3Q6ODAwMC9yb290LWNh
LmNlcjAzBgNVHR8ELDAqMCigJqAkhiJodHRwczovL2xvY2FsaG9zdDo4MDAwL3Jv
b3QtY2EuY3JsMAoGCCqGSM49BAMCA0cAMEQCIF/+Ggzw4Pm7OvCrcekUA1/zMk9B
e0L6M67T90dD0E1bAiAOeDfLu0bFCF4YANfOOkOL3howf8ZGsSkes5lYiDsyuQ==
-----END CERTIFICATE-----`;

  const pemCA = `-----BEGIN CERTIFICATE-----
MIIBlDCCATmgAwIBAgIUf2jj+cgKVMw5pD1GMocG1YpExEwwCgYIKoZIzj0EAwIw
JjEVMBMGA1UEAxMMUm9vdCBDQSBjZXJ0MQ0wCwYDVQQKEwRUZXN0MB4XDTIyMTIy
NjA2NDIwNloXDTQyMTIyNjA2NDIwNlowJjEVMBMGA1UEAxMMUm9vdCBDQSBjZXJ0
MQ0wCwYDVQQKEwRUZXN0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEO60ORwIK
ZfZ0wxiqf97Mezc28fVFVnuyNCnTNVm2iztE03K3ZrLD0rZuohvJmNvB1DdgZSJS
NHIYp7U8LnKh36NFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
AQEwHQYDVR0OBBYEFLlAZeqsu58hI2DV8kaz4aLR2YHbMAoGCCqGSM49BAMCA0kA
MEYCIQDNC+Qqd5qL0VFzc4Cpk5flsxWtADnKr+bO/QeX7f0VPwIhANUETaqaXkpj
Cuv/UlaFeXwPEDtbvhgY8FIBW8CNRLyA
-----END CERTIFICATE-----`;

  it("generating an OCSP request", async () => {
    const certificate = new x509.X509Certificate(pemLeaf);
    const issuer = new x509.X509Certificate(pemCA);

    const request = await x509.ocsp.OCSPRequestGenerator.create({
      certificate,
      issuer,
    });

    const pemRequest = request.toString("pem");
    assert.ok(pemRequest);
  });
});